### ISSUE TITLE
Support admin/non-admin NSIS installs

### ISSUE THREAD

**Issue by phargogh** [natcap/invest-workbench#107]
When we install InVEST's electron interface on Windows via its NSIS installer, it would be great to be able to support installation as a non-admin such as through `electron-builder`'s supplemental NSIS script.  This is related to https://github.com/natcap/invest/issues/21 and https://github.com/natcap/invest/pull/484, and so what we learn there should almost certainly apply here as we're still working with NSIS.

**Comment by davemfish** [comment]
This was resolved a while back, as the electron builder's config makes this behavior the default if we use:

```
nsis: {
    oneClick: false,
},
```
