### ISSUE TITLE
Save Python Script doesn't include logging

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest-workbench#109]
I noticed that when saving to a python script through the workbench it doesn't include the logging section. The model I tested was Annual Water Yield.

**Comment by davemfish** [comment]
Thanks, Doug. This reminded me that this issue exists https://github.com/natcap/invest/issues/237

And the proposed solution described there still sounds good to me.

**Comment by davemfish** [comment]
This is fixed because that linked invest issue was fixed.
