### ISSUE TITLE
Clicking "Open" on an untouched model inputs pane opens a new inputs pane

### ISSUE THREAD

**Issue by phargogh** [natcap/invest-workbench#112]
To reproduce:

* Open the workbench
* Open a model (I used Fisheries)
* Click the "open" button to attempt to load a set of input parameters into the existing pane
* Select the parameter set
* Observe that a new pane was opened, leaving the original, empty, pane open.

The behavior I'd expect is that if:

* The most recently-opened model has not been altered and
* The datastack selected is for the same model as what was just opened

Then it might be nice to load the parameters into the existing pane.  It's not a problem to manually close the existing tab down, but it is a slightly unexpected behavior.

**Comment by davemfish** [comment]
Yeah, I hear you. Over on #98 we talked about maybe having the "Open" button only accessible from the home screen to avoid this. Or like you suggest, we could probably figure out logically if it should open a new tab or populate the already-open one. 

Let's address this issue and #98 at the same time.

**Comment by davemfish** [comment]
This was fixed in #157
