### ISSUE TITLE
Graphically display model execution status in model tabs?

### ISSUE THREAD

**Issue by phargogh** [natcap/invest-workbench#113]
Since it's possible to run multiple InVEST models in parallel and in separate tabs, what if we were to display some sort of visual indicator of model run status (model executing/failed/completed) in the tab?

While running a few models in parallel, it was a little inconvenient to have to keep switching between tabs to see what the state of each model's execution was.

**Comment by davemfish** [comment]
Great idea! That status is also viewable from the home tab on each job's card. I agree we should display it visually on the tab, probably not with more text, but maybe an ✔️ ❌ :spinner: And the same cue can be applied to those recent job cards.

**Comment by dcdenu4** [comment]
✔️ 🟡  🚫
