### ISSUE TITLE
artifacts are not deploying to our releases bucket

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#114]
When builds happen on natcap's fork of the repo (e.g. on a PR's merge commit) artifacts should deploy to releases.naturalcapitalproject.org

That's not working, I think because we're referencing `github.actor` when we want `github.repository_owner`

When builds happen on our personal forks, they should upload to natcap-dev-build-artifacts bucket. And that does seem to be working, so long as you add the GCP secret to your github account.

**Comment by emlys** [comment]
I'm running into this as well trying to copy the signing certificate from google cloud. https://github.com/natcap/invest-workbench/runs/1920521126#step:12:10 Maybe something's wrong with the GOOGLE_SERVICE_ACC_KEY secret?

**Comment by emlys** [comment]
did we have secrets defined for this repo before? https://github.com/natcap/invest-workbench/settings/secrets/actions

**Comment by davemfish** [comment]
> did we have secrets defined for this repo before? https://github.com/natcap/invest-workbench/settings/secrets/actions

Hmm I guess it's possible we never did? My memory of doing it certainly can't be trusted

**Comment by emlys** [comment]
I think we need to create a new service account key and add it as a secret. reading through some google cloud docs now

**Comment by davemfish** [comment]
I think we need to add the secret, but we have a ton of keys stored on our team gdrive. I just added one that I think is the same one that's working on my fork.

**Comment by davemfish** [comment]
Not exactly sure how to test this before actually merging a PR.
