### ISSUE TITLE
Order the invest model list in a smart way

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#121]
Now, we're defaulting to the order returned by `invest list`, which is alphabetical, but might not actually alphabetize on the same form of the name that is displayed on the button.

Anyway, I think we can do better than alphabetizing. Some options to consider:

* Keep the user's frequently used models in a section at the top, alpha-sort for everything else
* Use usage logging data, or forum post data, to order the models by general popularity
* Sort models into sections by domain (Urban, Freshwater, Coastal, etc) This will certainly breakdown as some models are hard to classify. And those categories might mean a lot less to users than they do to us insiders. 
* Use the same method as the User's Guide - sections for Supporting, Final, Urban ES, & other tools. Personally, I don't find those headings to be useful.
* Alphabetize based on the same names that are displayed on the buttons.

Always keep CBC Preprocessor & CBC together, in that order.

**Comment by dcdenu4** [comment]
>     * Keep the user's frequently used models in a section at the top, alpha-sort for everything else

Love this idea.

>Sort models into sections by domain (Urban, Freshwater, Coastal, etc) This will certainly breakdown as some models are hard to classify. And those categories might mean a lot less to users than they do to us insiders.

This is what I initially thought as how to sort things better.

It's amazing how something seemingly so simple is tricky. I do like the idea of groupings ( AWY, SWY, SDR, NDR ) but that is subjective and hard to define. I feel like the easiest way is alphabetical with some rule breaking, as would be the case for CBC. 

But maybe that is fine if we had some *frequently used* section for the user.

**Comment by emlys** [comment]
I like the idea of a frequently/recently used models section above an alphabetic list. I'd suggest keeping the frequently used section to no more than 3 models, and also including them in the alphabetic list below, similar to the font selection dropdown in google docs.

**Comment by davemfish** [comment]
> Keep the user's frequently used models in a section at the top, alpha-sort for everything else

A few of us like this idea, but I think it's a bit redundant with the "recent jobs" section on the same tab. That effectively becomes a list of frequently used models. The only difference is that those buttons load a completed setup form instead of blank one. 

For now I've done a simple alpha-sort (with special CBC Preprocessor ordering). I'm also allowing the list to take two columns so that all models are visible onscreen. I think that makes the fancier sorting options less important.

**Comment by emlys** [comment]
>  it's a bit redundant with the "recent jobs" section on the same tab. That effectively becomes a list of frequently used models.

Good point! The simple alphabetical sort sounds good then.
