### ISSUE TITLE
App won't launch on macOS

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#137]
As described in #133, both @phargogh and I experienced this. Running `npm start` fails for me as well so it's not just an issue with the built app.
Ran `git bisect` and it seems the problem originated in [this commit](https://github.com/natcap/invest-workbench/commit/5179b3093a6f3cfc390836a70a53435311412bd9). Simply requesting the lock in the line `const gotTheLock = app.requestSingleInstanceLock();` triggers it.

Relevant info:
https://github.com/electron/electron-osx-sign/issues/223#issuecomment-611129476
https://github.com/electron/electron/issues/15958
Not sure why other people are having this issue specifically with Mac App Store builds. [This solution](https://github.com/electron/electron/issues/15958#issuecomment-447685065) may work for our case.

**Comment by davemfish** [comment]
Thanks for looking into this! Good to see it's a fairly simple explanation. Not good to see that there's no real fix, and only workarounds. If the workarounds don't seem appealing for some reason (I haven't looked at them closely myself) it could be worth deciding if we really want/need that `SingleInstanceLock` feature for macos.
