### ISSUE TITLE
switch from winston to electron-log for logging

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#141]
Here's a new bug in our winston logging: 

logger objects are instantiated from various modules, some running in `main` and some in `renderer`. But the logfile only seems to receive messages from loggers in one of those processes, not both. This is only a problem in the packaged application, not when running in development.

Anyway, at this point I'm not sure why we don't give up on `winston` and switch over to `electron-log`. I don't think I ever considered `electron-log`, maybe because I was searching for node logging modules, instead of electron logging modules?

https://www.npmjs.com/package/electron-log

**Comment by emlys** [comment]
my initial impression is that switching to `electron-log` would be a good change. just the fact that it has no dependencies is a plus. and I'm seeing `electron-log` recommended in several stackoverflow posts.

**Comment by dcdenu4** [comment]
> Also, it can be used without Electron in any node.js application.

This is great for a future web version!

**Comment by davemfish** [comment]
I'll more than likely make this switch as I work on #136 .
