### ISSUE TITLE
Translations: allow user to choose a language

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#148]
Add a UI component that lets a user choose from the available languages, and possibly upload their own message catalog. There are two groups of translatable text:
  1. Text that lives in natcap/invest-workbench (e.g. button labels)
  2. Text that comes from the invest server (e.g. model names, input descriptions) 
 
This should:
  1. change the language on the workbench side (not sure how/if gettext works with javascript)
  2. post to an endpoint created in natcap/invest#568, which should change the text on that side
  3. re-render the page, which should repeat any calls to the server, and so get the updated text.

How should we handle translating the relatively few strings that live in this repo ("Run", "Settings", ...)? I wonder if it would be easier to store their translations in natcap/invest with the others, and retrieve them from a new endpoint?

**Comment by davemfish** [comment]
>How should we handle translating the relatively few strings that live in this repo ("Run", "Settings", ...)? I wonder if it would be easier to store their translations in natcap/invest with the others, and retrieve them from a new endpoint?

Even apart from translation, it could be worthwhile to store all these strings as constants in a dedicated module in this repo. There are cases where strings are hardcoded in multiple places in tests where they are used in queries.

**Comment by davemfish** [comment]
Putting this on hold until the related invest infrastructure is in place, and because we're not targeting the beta milestone.

**Comment by emlys** [comment]
The `Accept-Language` request header is the first relevant thing I came across, but it seems like this is _not_ what we want:
> Browsers set adequate values for this header according to their user interface language and even if a user can change it, this happens rarely (and is frowned upon as it leads to fingerprinting).

> This header is a hint to be used when the server has no way of determining the language via another way, like a specific URL, that is controlled by an explicit user decision. It is recommended that the server never overrides an explicit decision. The content of the Accept-Language is often out of the control of the user (like when traveling and using an Internet Cafe in a different country); the user may also want to visit a page in another language than the locale of their user interface. 

(https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language)
