### ISSUE TITLE
Translations: the few strings that live in the workbench

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#159]
There are just a handful of words, mostly button labels, that appear in the UI and live on the workbench side. But these will be pretty high-impact and high-priority to translate because they enable basic interaction (run, cancel, etc.). 

It will probably be worth setting up `gettext` for the workbench, even if now the amount of translated text is small enough to handle without it.

**Comment by davemfish** [comment]
I think this is done in #174
