### ISSUE TITLE
material-design-icons failures on yarn install in GHA

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#170]
I believe this is the same issue as our past intermittent failures on `npm install` in GHA that inspired the switch to yarn. This is happening less often with yarn, but there's still occasionally a failure and I finally got some verbose logging from it:

```
verbose 198.444199837 Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:188:17)
error An unexpected error occurred: "https://registry.yarnpkg.com/material-design-icons/-/material-design-icons-3.0.1.tgz: unexpected end of file".
```

If it ever happens again, will be interesting to note if it's always `material-design-icons`. It's by far the biggest package we're installing. Here's the top 5 biggest in my local `node_modules`

```
356M	node_modules/material-design-icons
194M	node_modules/electron
178M	node_modules/react-devtools
105M	node_modules/app-builder-bin
12M	node_modules/@jest
```

**Comment by dcdenu4** [comment]
I've been using `react-icons` https://www.npmjs.com/package/react-icons for the web viewer. It says it unpacks to 36.6MB.
