### ISSUE TITLE
Habitat Quality empty args handling

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest-workbench#173]
When testing a recent PR for the Workbench I came across unexpected behavior in the Habitat Quality model. I was testing from a `package.json` file with InVEST ` "version": "3.9.1.post321+gf8ee8ff7"`.

When running HQ without an optional _Accessibility to Threats_ input I got the error from task `rasterize_access`:

```python
09/29/2021 10:03:57  taskgraph.Task     ERROR    Something went wrong when adding task rasterize_access (9), terminating taskgraph.
Traceback (most recent call last):
  File "taskgraph\Task.py", line 747, in add_task
  File "taskgraph\Task.py", line 1234, in _call
  File "pygeoprocessing\geoprocessing.py", line 2140, in rasterize
AttributeError: 'NoneType' object has no attribute 'GetLayer'
```

In the InVEST source code for HQ:
```python
    if 'access_vector_path' in args:
        LOGGER.debug("Rasterize Access vector")
        rasterize_access_task = task_graph.add_task(
         ...
            task_name='rasterize_access')
        access_task_list.append(rasterize_access_task)
```

Testing the recent release of InVEST 3.9.1 Qt, leaving the optional input empty apparently does not add it to the `args` input and the model runs successfully.

**Comment by dcdenu4** [comment]
I'm not sure if we have a standard for whether the UI should treat empty optional fields by not including in the args, or including them as empty. Thoughts?

**Comment by emlys** [comment]
I don't think we have a standard, but I'd vote to include them as empty, to be explicit.

**Comment by davemfish** [comment]
It's pretty common in invest to do something like:
`if 'access_vector_path' in args and args['access_vector_path']:`

I don't recall how this pattern first arose, but I think it's good because it de-couples `execute` from the UI a bit: whatever we decide to do in the UI will work in `execute`.

@dcdenu4 what do you think about moving this to an invest issue?

**Comment by phargogh** [comment]
I think this pattern arose from trying to make the python API as convenient to use as possible.  Handling optional parameters in this way allows someone calling an invest model to exclude an argument in multiple ways, including setting the args key to some falsey value like None.  That way you don't have to look up the args key again if you change your mind.

But @emlys is right, this is more of a convention than a standard.

**Comment by dcdenu4** [comment]
Moving to InVEST repo: https://github.com/natcap/invest/issues/675
