### ISSUE TITLE
settings dialog is unintuitive

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#200]
There are misc small things I'd like to improve about this UI:

![Capture](https://user-images.githubusercontent.com/4071255/142224303-3c0ea497-485b-408c-8c3a-dec8250a1f70.PNG)

A couple of the buttons have dedicated labels next to the button. We might as well put the label text on the button itself and remove some of the redundancy and clutter.

The Cancel & Save buttons only apply to the top section settings, so should be moved up to that section. But as @emlys suggested, it might be better to just automatically save on every change and do away with the save button. The Reset button then should also trigger a save. And Cancel could be replaced with an `X` in the upper right of the dialog.

**Comment by emlys** [comment]
@davemfish, I had removed the Cancel and Save buttons in #174, since it made it simpler to add the language selection dropdown. I didn't add an X to close though.
