### ISSUE TITLE
Improve drag-drop functionality on the setup form

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#37]
Right now it's possible to drag-drop an invest datastack file (or invest logfile) over the setup form and populate all the input fields at once from that datastack. What we're missing is the ability to drag-drop single files to populate single input fields, one at a time. 

The Qt interface supports both of these drag-drop abilities in an intuitive way. I think we should replicate that here.

**Comment by dcdenu4** [comment]
I'm on it!
