### ISSUE TITLE
avoid conflicts in port number when starting Flask app

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#42]
We need to check if the port is in use before trying to start the Flask app. Important for lots of reasons, including being able to launch multiple instances of the workbench or being able to run portions of the test suite while the electron app is also running.

Also, I don't think I ever finished making the port configureable with an environment variable. We should do that too.

**Comment by dcdenu4** [comment]
I set out to work on this and get more familiar with the workbench. In doing so I found myself a little confused between how environment variables are shared or available across the server / client boundary. 

For checking whether a port was available I thought the best way was for `server.py` to try to bind to the given port and if an OSError was thrown, then increment one until it was successful. This seemed fine, but then I needed the client to somehow know what the determined port would be. 

So I'm trying to figure out how to juggle that information and am currently trying to manipulate environment variables to do so. But it's not clear to me if `main_helper.js` and `server.py` share common env vars.

**Comment by davemfish** [comment]
Hey @dcdenu4 , I think there's probably a few options. I haven't thought through them yet, but here's some things that might be helpful.

* the flask app is launched as a child process by a `spawn` call from node (aka the "main" electron process). `spawn` can take an env object to set env vars for the child process.
* data can be shared across the two electron processes ("main" and "renderer") through IPC. There's an example of that sharing the invest exe path in `main.js` and `index.js`. The global node `process` variable can also be accessed from main & renderer, though only via the `remote` module, which is controversial. See #45

**Comment by davemfish** [comment]
This is resolved in #72
