### ISSUE TITLE
consider not using electron's remote module

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#45]
Electron has decided to deprecate it's `remote` module, but it will live on in "electron-userland" - meaning it will be maintained (or not) by volunteers going forward. 'remote' is a wrapper around IPC calls that allows communication between the `main` and `renderer` processes.

https://github.com/electron/electron/issues/21408

Some think there are security & performance concerns with `remote`
https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31

Other's are less concerned (2nd half of article)
https://medium.com/better-programming/2020-005-electron-apps-are-getting-faster-and-safer-3c045c39f61f

**Comment by emlys** [comment]
I just read through that issue thread and wow, people have a lot of opinions on this one. If they do end up moving it to `electron-userland`, I would think we should switch to using `ipc` directly. How about putting this issue on hold until they finalize that decision?

**Comment by davemfish** [comment]
Haha, yes indeed. 

I agree, using `ipc` directly seems like a good idea. There's been a couple cases where I used `ipc` instead of `remote` for new things as they came up, but haven't prioritized refactoring the existing `remote` uses. So yeah, I think this can go on hold, but I'd say we should not add any new `remote` code. Thanks for your input!

**Comment by dcdenu4** [comment]
Interesting reads. I think I fell in the Joe Honton, `remote` isn't that harmful if used correctly, camp. But, it doesn't seem to matter! It has been deprecated as of v12 https://www.electronjs.org/releases/stable?version=12 and they make it pretty clear that the `remote` module replacement (https://github.com/electron/remote) shouldn't be used:

>⚠️ Warning! This module has many subtle pitfalls. There is almost always a better way to accomplish your task than using this module. For example, ipcRenderer.invoke can serve many common use cases.
