### ISSUE TITLE
invest sample data distribution

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#54]
Right now, invest sample data is distributed only to Windows users during invest installation. The distribution is wrapped up in the NSIS installer.

For the workbench, we probably could still use an NSIS installer to install the workbench and offer sample data downloads to users. But, I think it would be really nice to design a cross-platform way to distribute sample data. 

If we want the sample data included with downloads of the workbench, it might be possible to do that with electron-builder. Though the data might end up buried somewhere in the application's installation folder (.App on macOS). 

**So it might be nicer - and simpler - to design a UI feature for fetching sample data on demand.**

**Comment by phargogh** [comment]
This would be great to have!  And also, thinking ahead to the data platform, this model of downloading the data needed for an analysis will probably be a common part of a workflow.

One thing that came up really recently was about the distribution of sample data to internet-poor areas, and it would be great if we could be sure to handle this use case as well.

**Comment by davemfish** [comment]
I started a design doc for this feature: https://docs.google.com/document/d/1othjTxKyHiTZni8NFed5eHZhjx4nXbXVeu_r6QkwQs4/edit?usp=sharing
