### ISSUE TITLE
Can't open CBC, CBC preprocessor, DelineateIt

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#63]
When I `npm start` and click on CBC, CBC Preprocesser, or DelineateIt, the model does not load and I get the following console errors:

```
/Users/emily/invest-workbench/node_modules/react-dom/cjs/react-dom.development.js:19504 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SetupTab.componentDidMount (index.jsx? [sm]:41)
    ...
/Users/emily/invest-workbench/node_modules/react-dom/cjs/react-dom.development.js:19527 The above error occurred in the <SetupTab> component:
    in SetupTab (created by InvestJob)
    in div (created by TabPane)
    in Transition (created by Fade)
    in Fade (created by TabPane)
    ...
/Users/emily/invest-workbench/node_modules/@babel/runtime/helpers/asyncToGenerator.js:6 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at SetupTab.componentDidMount (index.jsx? [sm]:41)
    ...
```

**Comment by phargogh** [comment]
FWIW, I bet the CBC and CBC-preprocessor are failing because of the presences of 'other' input types in `ARGS_SPEC`, which reflect the presence of the `Multi` inputs that have been removed in the dev version of CBC and will be in `release/3.9` soon.

**Comment by emlys** [comment]
You're right! Confirmed that the Delineateit issue was fixed in https://github.com/natcap/invest/pull/364, and CBC issues are indeed due to the 'other' types.
