### ISSUE TITLE
Drop the electron-builder Actions script

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#65]
@emlys  pointed out some very valid concerns about using the samuelmeuli/action-electron-builder script for code signing:

> 1. Since it's not our repo, it's hypothetically possible that it could become insecure and expose the certificate and password
> 2. The built in code signing steps rely on us storing the certificate, base64 encoded, in github secrets. There's nothing wrong with this except it goes against our pattern of storing that stuff in Google Cloud

Looking at the actions script (https://github.com/samuelmeuli/action-electron-builder/blob/master/index.js), there's really not much to it, so here's an issue to just create our own script for these purposes.

**Comment by davemfish** [comment]
This will encompass #28 , but it's larger than that so I made a separate issue.

**Comment by emlys** [comment]
Thanks for making an issue for this! I started working on it related to #28, and it looks like having the `electron-builder build` command in our actions YML will be pretty straightforward and easier to maintain.
