### ISSUE TITLE
Add taskgraph cache directory as global invest setting

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest-workbench#69]
It would be nice to have an option for deciding which taskgraph cache directory to use across model runs so that different workspaces can be used while still gaining the benefit of not repeating calculations.

This relates to the InVEST issue number 7 https://github.com/natcap/invest/issues/7. 

This issue might be a good time to also work on issue #43 , related to saving these global settings.

**Comment by dcdenu4** [comment]
Putting on hold and might ultimately mark invalid.
See this InVEST issue https://github.com/natcap/invest/issues/7

**Comment by davemfish** [comment]
Closing because invest and taskgraph do not support this. See the invest issue linked above.
