### ISSUE TITLE
Resolve security warnings from github

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#76]
I'm seeing a message from github warning about the following dependencies:
* vega
* node-notifier
* ini
Hopefully we can just update to a later version to resolve this.

**Comment by davemfish** [comment]
We're not actually using `vega` right now. I think I was using it before we put the results visualization stuff on hold, so I should have dropped the dependency then. 

I'm not certain which of our dependencies is requiring those other two.

**Comment by emlys** [comment]
Marking as "wontfix" since the warnings have mysteriously disappeared (https://github.com/natcap/invest-workbench/security/dependabot). Not sure whether this means the problem is actually solved, but if this happens again, it seems like the best way to force a certain version of a nested dependency is with an `npm-shrinkwrap.json` file.
