### ISSUE TITLE
Figure out how to push updates to users

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#77]
It would be nice to allow workbench updates in the style of modern browser updates, where new files seem to be patched into an existing installation. As opposed to installing a whole separate instance of the application and uninstalling the older one.

The extra resources of the python binaries _might_ make this more complicated, or maybe there's really nothing special about that in this context.

**Comment by dcdenu4** [comment]
https://www.electronjs.org/docs/tutorial/updates

**Comment by davemfish** [comment]
The auto-update looks great for pushing updates of the Workbench (i.e. the UI layer of invest), but I'm not sure if it's a good idea to also automatically push updates of `natcap.invest` (i.e. the invest models). Perhaps auto bugfix updates for invest are okay. But for the sake of scientific reproducibility, I think users should have a lot of control over which version of invest they run and when exactly they decide to switch versions.

**Comment by phargogh** [comment]
Yep, I agree ... users should control (or at a minimum, confirm) updating to a newer version of InVEST.  Updating even to a new bugfix release sounds like a minefield since there could easily be something like a packaged dependency update that changes results.

**Comment by davemfish** [comment]
There's some related discussion over on #29 . We decided it would be nice if the workbench can do auto-updates that don't overwrite the invest binaries part of the app's resources. So if a workbench update comes with a newer version of invest, then it will add to the available invest versions that the workbench can run.

**Comment by davemfish** [comment]
After getting the autoUpdater working, it's clear that our idea to avoid overwriting the invest binaries during an update does not work. Everything in the app's `resources` directory is cleared out and replaced during the update. And I think that behavior is from squirrel and probably not configurable. 

If we want invest binaries to persist across updates - so that multiple versions of invest can be managed by the workbench - we might need to store them somewhere else, like `userData`. And that might mean "installing" those invest binaries separately from the installing the workbench. 

I think it's worth considering our requirements again before engineering something.

**Comment by davemfish** [comment]
A couple clear requirements:
1. user's should have full control over when they want to update `natcap.invest` - no surprise/silent updates
2. users (and especially devs) should easily be able to have multiple versions installed. I often want the latest official release installed and want to be able to install & test a dev build without clobbering my other installation.

Without doing anything fancy, we can achieve this by managing workbench updates the same way we manage invest updates now: install new versions to a new install directory. For example, the install path can vary by invest version string, which is referenced in `package.json` `invest.version`. That means workbench updates that don't include a different `natcap.invest` version _will_ overwrite an existing workbench. If that's undesirable, we can always vary the install path by workbench version string as well.
