### ISSUE TITLE
Update to InVEST 3.9.0

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#80]
Update the workbench to be compatible with 3.9.0. The CBC model at least needs to have the UI spec updated.

**Comment by davemfish** [comment]
Thanks for pointing this out. I'm just now merging natcap/invest `main` into `release/workbench-alpha`. https://github.com/natcap/invest/pull/441

So that may effectively take care of this on the invest side. And then in this repo we'll need to point to the binaries produced by that PR.
