### ISSUE TITLE
Revisit control_target and control_option UI spec properties

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#81]
* `control_option` is not being applied to all input types
* I'm not sure we can adequately represent the dependencies between input fields that we have in the QT interface. For instance in CBC, both the "do_valuation" and "use_price_table" checkboxes have to be checked for the "price_table" field to be enabled. Not sure that's possible with only one `control_option` property.
<img width="358" alt="image" src="https://user-images.githubusercontent.com/43770515/104503285-162a5980-559e-11eb-86fc-98a914b2808b.png">

* As I'm understanding the `toggleDependentInputs` function:

   - if the value in the controlling input field is falsy, then apply the `control_option` style (e.g. 'disabled') to the controlled field
   - if the value in the controlling input field is truthy, then set the controlled field styling to undefined (normal).
   I don't think this can represent the opposite relationship: if the "use price table" box is checked, then the "price" field is disabled.

It would be nice to be able to represent any combination of AND, OR, NOT operators on input fields. Maybe the UI spec could have something like:
`"price": {"(NOT do_valuation) OR use_price_table": "disable"}`

**Comment by davemfish** [comment]
This is interesting. You're right that we're pretty limited in the relationships we can capture with the current uiSpec options. And you're reading of that toggle function sounds right. Refactoring that may certainly be in order. I like your idea to support stuff like this `"price": {"(NOT do_valuation) OR use_price_table": "disable"}` if we have a need for it.

It reminds me a lot of how validation handles optional arguments as defined in the `ARGS_SPEC` `required` property. So there's probably lessons to be learned there, if not actual functions to be re-used.

> if the "use price table" box is checked, then the "price" field is disabled.

This sounds like something that should be supported but isn't. For what it's worth, I think the model will function correctly (using the price table and ignoring the price field) even if price field was enabled and given a value. Even so, I agree this field should disable in this case.

> both the "do_valuation" and "use_price_table" checkboxes have to be checked for the "price_table" field to be enabled.

This sounds like something that could be supported already: 
If the `do_economic_analysis` checkbox controls the entire group of econ-related inputs, including the `use_price_table` checkbox, then that hierarchy would require both boxes to be checked for "price_table" to be enabled. And that's actually how it's structured in the Qt UI. 

> control_option is not being applied to all input types
Not sure what you mean here, can you elaborate?

**Comment by emlys** [comment]
> This sounds like something that could be supported already:

You're right, that makes sense

>> control_option is not being applied to all input types

> Not sure what you mean here, can you elaborate?

In [ArgInput/index.jsx](https://github.com/natcap/invest-workbench/blob/39d4c889ac7dffcb3f8e5cb89514e5c3a1a39a72/src/components/SetupTab/ArgInput/index.jsx#L103), `className={arg-${ui_option}}` isn't set for boolean type inputs, so they don't get disabled

**Comment by davemfish** [comment]
> In [ArgInput/index.jsx](https://github.com/natcap/invest-workbench/blob/39d4c889ac7dffcb3f8e5cb89514e5c3a1a39a72/src/components/SetupTab/ArgInput/index.jsx#L103), `className={arg-${ui_option}}` isn't set for boolean type inputs, so they don't get disabled
> 
> I'm going to go through all the models and see what kinds of logical dependencies there are, so we can decide how to implement that.

Ahh yes. I probably hadn't come across a boolean input that needed to be controlled, but now we have (at least) one.

**Comment by emlys** [comment]
Here are some observations about the dependencies between fields we have in the QT interface:
* A lot of models have no dependencies
* The most common kind of relationship is: sufficiency of A determines interactivity of B.
    - If A is sufficient, B is interactive; if A is not sufficient, B is not interactive
    - 'A is sufficient' means that (1) A is interactive; and (2) A has a value if it's a text input, or is true/checked if it's a boolean input.
    - The current implementation in the workbench checks the value's truthiness, but not whether it's interactive.
* A few models (CBC, DelineateIt, Fisheries, GLOBIO, SWY, Wind Energy) have the opposite relationship:
    - If A is sufficient, B is not interactive; if A is not sufficient, B is interactive.
    - This is not implemented in the workbench.
* Two models (Coastal Vulnerability, Finfish) have a dependency that's more complicated than enabling/disabling fields. 
    - Field A is a path to a vector. Field B is a dropdown menu When A is sufficient, it opens the vector, reads in the column names, and sets B's dropdown options to those names.
    - There's a small bug here: if the value of A is sufficient, and then it's replaced with a new value that's also sufficient, the sufficiency hasn't changed, so no signal gets emitted and it doesn't read in the new column names.
* Two models (Fisheries, UCM) have a dependency where the value of a dropdown field (not its sufficiency) determines whether other fields are enabled/disabled.
* There's some inconsistency with boolean inputs. 
    - In some places we have a checkbox input whose value controls interactivity of other fields
    - In others, we have a Container whose expanded/collapsed state is a boolean arg (e.g. in Finfish the 'Enable Uncertainty Analysis' container corresponds to the arg `use_uncertainty`. It is not connected to other fields directly, but they aren't accessible when the container is collapsed.
    - In others, we have a Container that doesn't correspond to any arg (e.g. in Urban Cooling, the 'Manually adjust cooling capacity' section). There is no boolean arg for it. It decides whether or not to manually adjust cooling capacity based on whether the args _within_ the section (shade, albedo, et0) have values.
    - In others, we have a Container that's always expanded. It's just for visually grouping some fields together. (e.g. 'Population Parameters' and 'Recruitment Parameters' in Fisheries).

**Comment by dcdenu4** [comment]
That's some great reporting. I just wanted to pop in and say that I'd love to see consistency brought to how we handle these interactions across models.

**Comment by davemfish** [comment]
Thanks for this rundown! A few specific comments

> If A is sufficient, B is not interactive; if A is not sufficient, B is interactive.

Seems pretty clear now that we should support this.

> Field A is a path to a vector. Field B is a dropdown menu When A is sufficient, it opens the vector, reads in the column names, and sets B's dropdown options to those names.

This could be a trickier one, but sounds like we should figure it out. When a dropdown input has static options, they are defined in the ARGS_SPEC, but here we want a dynamic options list. 

> Two models (Fisheries, UCM) have a dependency where the value of a dropdown field (not its sufficiency) determines whether other fields are enabled/disabled.

It makes sense to support this - determining interactivity based on values rather than just sufficiency. 

Finally, I agree with Doug, it would be nice to eliminate some of the inconsistencies across models while we have the chance. I don't think the goal needs to be exactly reproducing the old Qt UI, input for input. We need to reproduce all the functionality, but if there's a way to improve on the old designs, with different ordering, grouping, changing input types, etc, we should go for it.

**Comment by davemfish** [comment]
This is no longer an issue after the refactor in #84
