### ISSUE TITLE
invest log messages do not display in real-time

### ISSUE THREAD

**Issue by davemfish** [natcap/invest-workbench#86]
I just noticed this on Windows (didn't seem to notice when developing on linux). The log component uses npm `tail` package (mimic of unix `tail`) to stream lines from the invest logfile on disk to the react component. The problem is, the lines tend to come in large chunks, rather than line-by-line, even when configured to "watch" or "follow" the file. No lines are missed, but the `Tail` doesn't seem to keep up with every change to the file.

I briefly tried npm's `better-tail`, but saw basically the same results.

If I use the actual unix `tail -f` to tail the same logfile in a shell at the same time, the node `tail` _does_ keep up and the log component updates with each new line as desired. So it seems like some OS-level filesystem events are behind this issue.

It may have been a bad decision to render the logfile by streaming from the file on disk. Another option is to listen to the stdout of the invest subprocess. The only challenge there is when re-loading a saved invest job, the stdout data is not available, so the invest log would still need to be read from the file on disk. But, at least in that case the file is not still being actively appended to.

So, I'm thinking a good solution is to 1) drop npm `tail` and `better-tail` dependencies. 2) Render "running" invest logs by listening to invest's stdout stream and 3) Render pre-existing "complete" invest logs - from a saved job - by reading in the whole file.

**Comment by phargogh** [comment]
For future self, I got a binary build working for the workbench by:

1.  Downloading and extracting the DMG from https://github.com/natcap/invest/runs/1750819837
2. Pulling out the `invest_dist` directory from the `.app` bundle and placing it in `<workbench repo root>/build/`, renaming `invest_dist` to `invest`
3. Removing Apple's quarantine tag with `find build/invest -name "*.so" -o -name "*.dylib" | xargs xattr -d com.apple.quarantine`
4. `npm start`

**Comment by phargogh** [comment]
Working on this in `bugfix/86-log-messages-display-delayed`.

**Comment by davemfish** [comment]
> For future self, I got a binary build working for the workbench by:
> 
> 1. Downloading and extracting the DMG from https://github.com/natcap/invest/runs/1750819837
> 2. Pulling out the `invest_dist` directory from the `.app` bundle and placing it in `<workbench repo root>/build/`, renaming `invest_dist` to `invest`
> 3. Removing Apple's quarantine tag with `find build/invest -name "*.so" -o -name "*.dylib" | xargs xattr -d com.apple.quarantine`
> 4. `npm start`

Woah, @phargogh, this sounds a lot harder than it should be! Did you run into problems with `npm run fetch-invest`?

**Comment by phargogh** [comment]
I was, but they seem to have resolved themselves for now!  For some reason, the server doesn't always want to start within the allowed startup time, yet when launching the binaries directly the server starts up quickly (< 2s).  I'm not yet sure what's going on there.  Nothing is showing up in the system log at the moment.

When I tried it with getting the DMG and doing all of that stuff above, the binaries worked on the first go (Big Sur environment variable issues aside).

I also tried to get the binaries via `npm fetch-invest`, which my late-afternoon brain thought was perfectly sensible.

**Comment by phargogh** [comment]
In a rather bizarre turn of events, it would appear that on Windows, the OS might not be reporting back to the process calling `fs.watch` with the frequency we expect.  Calling GNU `tail` on the logfile while a model is running causes NOT ONLY the tail of the file to be printed to stdout, but ALSO to be recorded in the logfile pane in the workbench itself.

It is currently unclear if this is a bug in `node-tail` or in Windows, but it is unexpected either way.

**Comment by phargogh** [comment]
Pending #89
