### ISSUE TITLE
Some minor UI issues

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#87]
A catch-all ticket for some small UI things that would improve the appearance but don't affect usability. Feel free to add anything else you notice!

- [x] More clearly indicate if an input is optional. In the QT implementation the label text would contain "(optional)". Since we're now getting the label text from the args spec, it should be possible to append "(optional)" to the label if `argsSpec.arg.required === false`.
- [x] Disabled inputs still sometimes have a red or green outline, and any text typed into them before disabling (or selected dropdown option) isn't grayed out. This makes it less obvious that they're disabled.
- [x] input labels have inconsistent capitalization
- [x] Dropdowns should expand to fill the available width like text fields do, or at least expand to fit their widest option.
- [x] The style for separating groups of inputs isn't super effective because when the longer input labels wrap onto multiple lines, that introduces extra space that looks just like the between-group margin. Try making the margin bigger or add a faint horizontal bar or background color.
- [x] Some UI elements don't handle resizing of window well. Should the window just scroll vertically / horizontally when shrunk too much?
- [x] There's a gray border line above the top model in the list of models. IMO there should only be borders between models.
- [ ] It's inconsistent which text is selectable. If you "Select All" on the home tab, the model names aren't selected. If you "Select All" on a model tab, "User's Guide" and "Frequently Asked Questions" are selected but "Load parameters from file", "Save to JSON", "Save to Python script" are not.
- [x] Default hover text appears on all elements and is not helpful. We should remove it and maybe add it back for elements that would really benefit from it.
- [x] Open Workspace button opens a native OS dialog, but on Windows it does not display on top of other open windows. So it's easy to think that the button didn't work.
- [ ] ~~input text fields should display the right-most end of their text content when they contain text that is too long to display completely. That way the more important part of the filepaths is always visible. This was implemented at some point but seems to no longer be working.~~ Moving this to a new issue.

**Comment by davemfish** [comment]
Great list!

> If you hold down a key in a text input field, it only types the character once. Not really a problem, but different from the expected behavior in a form.

This one I'm not seeing in `main`, if I'm interpreting it correctly.

**Comment by emlys** [comment]
@davemfish it turns out that is just a default macOS thing that I'd never noticed before 😬

**Comment by davemfish** [comment]
> @davemfish it turns out that is just a default macOS thing that I'd never noticed before 😬

Woah, that's a new one!

**Comment by davemfish** [comment]
I've checked off a couple of these items as I also work on #122 . I didn't touch any of the args form related bullets. So I'll also leave this issue open and rename it according to what's left.
