### ISSUE TITLE
Cannot open mac binaries

### ISSUE THREAD

**Issue by emlys** [natcap/invest-workbench#94]
To reproduce:
1. Download the `invest-workbench-macos-latest` artifact from https://github.com/natcap/invest-workbench/actions/runs/520960147 and unzip the file.
2.  Open (double-click or right-click > open). A message appears _"The application "InVEST Workbench" can't be opened"_. 

We are not signing the workbench binaries for mac. The message is different that what you'd get if the problem is due to a missing/expired/revoked certificate. Most likely something is wrong with the binaries or the app bundle structure.

**Comment by davemfish** [comment]
I wonder if we're experiencing this: https://github.com/electron-userland/electron-builder/issues/4299

Also I know we've talked about zip vs dmg in the past, but I can't remember any arguments for/against. Is it worth switching the target to a dmg to see what happens?

**Comment by davemfish** [comment]
@emlys here's a dmg, do you mind testing it whenever it's convenient? https://github.com/davemfish/invest-workbench/suites/1929236312/artifacts/38042877

**Comment by emlys** [comment]
@davemfish Yay, that works! I'm in favor of DMGs in general because it seems to be the most common format for apps distributed outside the app store, and you can set the background image to instruct users to drag-and-drop into the Applications directory.
