### ISSUE TITLE
Add load option next to save options

### ISSUE THREAD

**Issue by dcdenu4** [natcap/invest-workbench#98]
When a model tab is open there are save options in the left column. I would expect a load option there as well, that would file browse to a parameter file and update the current model inputs. The Load button up top creates a new `InvestJob` and calls `openInvestModel(job)`.

Proposal
----------
Add `Load saved parameters` under the save options. Clicking would open a file browser and expect a `json` parameter file. On submit, the inputs would be batch updated like what occurs when a parameter json file is dropped on the model.

**Comment by davemfish** [comment]
Sounds like a good idea to me. As part of this we could also rename the existing "Load Parameters" button to "Open" and consider moving it to the home tab so it's not accessible at the same time as this new "Load" button.

**Comment by davemfish** [comment]
Marked it for the beta release because I don't think it's critical to be shipped with alpha. But that doesn't mean we need to wait to work on this, and if it's finished before we've done the alpha release, then that's great too.

**Comment by dcdenu4** [comment]
This is a comment from @emlys over on #90 

If you're on the Home tab:
* drag-and-dropping a file should open a new model tab and populate it
* selecting a file via the "Load Parameters/Open" button should open a new model tab and populate it

If you're on a model tab:
* drag-and-dropping a file:
  * if the file is for the model that's open: populate the model form
  * if the file is for a different model: error? or open and populate a new model tab?
* selecting a file via the "Load Parameters/Open" button should open a new model tab and populate it
  * maybe this button only belongs on the Home screen?
* "Load" button in sidebar:
  * if the file is for the model that's open: populate the model form
  * if the file is for a different model: error? or open and populate a new model tab?   

I feel like having both a "Load" button in the sidebar and an "Open" button at the top of a model tab is kind of redundant. Since you have to go back to Home to open a new model tab in the usual way, what if the "Open" option also lived on the Home page? 
We could also put "Open" and "Open in new tab" in the custom menu bar File menu, so you could still access it from anywhere.
